steps:
 - name: ':jekyll: :book:'
   command: .buildkite/steps/build.sh
   branches: master
   env:
     PROJECT: book.csmi
 - name: ':rocket: :book:'
   command: .buildkite/steps/deploy.sh
   branches: master
   env:
     PROJECT: book.csmi
