= Documentation
:imagesdir: images/
:pilotsdir: docs/pilots/
include::docs/includes/header.adoc[]

[TIP]
====
This book is writen in asciidoc.  You can compile it in HTML using the
asciidoctor compiler, see
link::http://asciidoctor.org/docs/install-toolchain/[how to install
asciidoctor]. Then just type `make` for fast html compiling.
You can also preview the document via a browser plugin
(link::https://addons.mozilla.org/fr/firefox/addon/asciidoctorjs-live-preview/[firefox], 
link::https://chrome.google.com/webstore/detail/asciidoctorjs-live-previe/iaalpfgpbocpdfblpnhhgllgbdbchmia[chrome]).
For the plugin, you have to open the raw file (click RAW button).
See for example this link::https://raw.githubusercontent.com/MSO4SC/book.mso4sc.eu/master/README.adoc[README].
====

== Introduction

This book presents student's intership reports

== Reports 2017

==== Master 1

ifdef::env-github[===== link:docs/2017/m1/roger-paulin/README.adoc[Roger-Paulin]]
ifndef::env-github[===== link:/2017/m1/roger-paulin/[Roger-Paulin]]


ifdef::env-github[===== link:docs/2017/m1/chifaa-dahik/README.adoc[Chifaa-dahik]]
ifndef::env-github[===== link:/2017/m1/chifaa-dahik/[Chifaa-dahik]]


== Contribute to this documentation

. Create a fork on github of the repository https://github.com/cemosis/book.csmi.eu.
(Top right button). It will create a repository in your account
. Clone your own book.csmi.eu
[source]
----
git clone https://github.com/<username>/book.csmi.eu
----
. Edit the book (./docs/*.adoc files) as usual (git add/commit/push).
. Then create a Pull Request on github from your fork repository to the original one.


:INFO: To pull for original repository
link:https://help.github.com/articles/syncing-a-fork/[see the fork
documentation]

== Compiling the book

==== Installing the toolchain

install `ruby` and  `bundle`

----
# On MacOSX
brew install ruby
gem install rake bundle

# on debian/ubuntu
apt-get install ruby-bundler
----

then run `bundle` in the top level directory of the book
----
bundle
----

NOTE: it installs all the requirements

then type

----
bundle exec jekyll serve
----

Or just `make serve`

NOTE: it starts a link:http://127.0.0.1:4000/[local web server] on the
port 4000 where you can read the book.

